export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  UPDATE_CART: "UPDATE_CART",
};
